project_id = "atkektzlfijvoyuexqes"

[functions.gemini-token]
verify_jwt = false

[functions.analyze-youtube]
verify_jwt = false

[functions.openai-realtime-token]
verify_jwt = false

[functions.transcribe-video]
verify_jwt = false